### ISSUE TITLE
 Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [huwdp/huwinterpreter-mirror#1]
https://github.com/huwdp/huwinterpreter-mirror/blob/682c968c43f794dec2ab8335024b06e8c3ae32b1/deploy-appimage/build-app-image.sh#L5

Please provide the AppImage for download on GitHub Releases, thanks.

**Comment by huwdp** [comment]
Done.
Thanks for your awesome work with linuxdeployqt!
