### ISSUE TITLE
Incorrect AppImage header

### ISSUE THREAD

**Issue by probonopd** [huwdp/huwinterpreter-mirror#2]
The file provided for download does not have the correct header (the magic bytes `0x414902` are missing at offset 8). Can you please try again with the latest continuous build of linuxdeployqt? (This was broken for a short time in our continuous builds). 

Incorrect:

```
0000000: 7f45 4c46 0201 0103 0000 0000 0000 0000  .ELF............
0000010: 0200 3e00 0100 0000 c072 4000 0000 0000  ..>......r@.....
0000020: 4000 0000 0000 0000 b898 1e00 0000 0000  @...............
```

cc @TheAssassin

Reference:
https://github.com/AppImage/appimage.github.io/pull/800

**Comment by huwdp** [comment]
Hi, I updated my linuxdeployqt file, redeployed the release and uploaded release in GitHub (same link).
